require('options')
require('keymaps')
require('plugins.lazy')
require('plugins.lualine')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.keymaps')
require('plugins.options')
require('plugins.nvim-tree')
require('plugins.tele')
-- require('plugins.conform')

-- require('plugins.obsidian')
-- require('plugins.zenmode')
